services:
  monitor:
    image: juan523/monitoragent
    ports:
      - "3000:3000"
    privileged: true
    environment:
      HOST: "34.42.61.185" # always copy the IP address from the monitoringapi vm in GCP
    volumes:
      - /proc:/proc
    restart: always
